apiVersion: v1
kind: Secret
metadata:
  name: agrosolutions-property-secret
type: Opaque
stringData:
  Messaging__Username: guest
  Messaging__Password: guest
  Jwt__Secret: -f6(3grZF0@BLt4tkXOQ~*3+Z2j)[k%jpj/<Wa2]l@[*+^zhRw
  ConnectionStrings__DefaultConnection: Server=agrosolutions-property-sqlserver,1433;Database=AgroSolutionsProperty;User Id=sa;Password=Users!Passw0rd;TrustServerCertificate=True
